AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket for Cloud Resume Challenge

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

