name: Deploy Update to S3
run-name: ${{ github.actor }} Updated CV Website
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Update to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: eu-west-1
      - name: Deploy Update to S3
        run: aws s3 sync . s3://alisam-cv-bucket